module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      lg2: "1100px",
      xl: "1440px",
    },
    colors: {
      primary: "#0AA1DD",
      secondary: "#00FFC6",
      white: "#FFFFFF",
      black: "#000000",
      dark: "#002243",
      gray: {
        100: "#131821",
        50: "#4D4A4F",
        40: "#D1D1D1",
        30: "#DFDFDE",
        20: "#F2F2F2",
        10: "#FBFBFB",
      },
      blue: {
        100: "#2155CD",
        70: "#0AA1DD",
        40: "#79DAE8",
        20: "#E8F9FD",
      },
      red: "#c93d62",
    },
    fontSize: {
      xxs: "10px",
      xs: "12px",
      sm: "14px",
      base: "16px",
      md: "18px",
      lg: "22px",
      xl: "28px",
      "2xl": "32px",
      "3xl": "48px",
      "4xl": "56px",
      "5xl": "72px",
    },
    fontFamily: {
      heavy: ["Font-Heavy", "sans-serif"],
      extrabold: ["Font-ExtraBold", "sans-serif"],
      bold: ["Font-Bold", "sans-serif"],
      semibold: ["Font-SemiBold", "sans-serif"],
      medium: ["Font-Medium", "sans-serif"],
      regular: ["Font-Regular", "sans-serif"],
      thin: ["Font-Thin", "sans-serif"],
      ultralight: ["Font-UltraLight", "sans-serif"],
    },
    extend: {},
  },
  plugins: [],
};
